export const exact = {
  "malterlib-enum": ["memory_order"],
  "malterlib-enumerator": [
    "memory_order_acq_rel",
    "memory_order_acquire",
    "memory_order_consume",
    "memory_order_relaxed",
    "memory_order_release",
    "memory_order_seq_cst",
  ],
  "malterlib-function": [
    "allocate_shared",
    "bind",
    "const_pointer_cast",
    "declval",
    "dynamic_pointer_cast",
    "forward",
    "forward_as_tuple",
    "get_deleter",
    "getline",
    "make_pair",
    "make_shared",
    "make_tuple",
    "max",
    "min",
    "move",
    "move_if_noexcept",
    "static_pointer_cast",
    "tie",
    "tuple_cat",
  ],
  "malterlib-keyword-access": ["friend", "private", "protected", "public"],
  "malterlib-keyword-auto": ["auto"],
  "malterlib-keyword-builtin-character-types": [
    "__wchar_t",
    "ch16",
    "ch32",
    "ch8",
    "char",
    "char16_t",
    "char32_t",
    "uch16",
    "uch32",
    "uch8",
    "wchar_t",
    "zch16",
    "zch32",
    "zch8",
    "zuch16",
    "zuch32",
    "zuch8",
  ],
  "malterlib-keyword-builtin-constants": ["NULL", "false", "nullptr", "true"],
  "malterlib-keyword-builtin-float-types": [
    "double",
    "float",
    "fp1024",
    "fp128",
    "fp16",
    "fp2048",
    "fp256",
    "fp32",
    "fp4096",
    "fp512",
    "fp64",
    "fp8",
    "fp80",
    "ufp1024",
    "ufp128",
    "ufp16",
    "ufp2048",
    "ufp256",
    "ufp32",
    "ufp4096",
    "ufp512",
    "ufp64",
    "ufp8",
    "ufp80",
    "zfp1024",
    "zfp128",
    "zfp16",
    "zfp2048",
    "zfp256",
    "zfp32",
    "zfp4096",
    "zfp512",
    "zfp64",
    "zfp8",
    "zfp80",
    "zufp1024",
    "zufp128",
    "zufp16",
    "zufp2048",
    "zufp256",
    "zufp32",
    "zufp4096",
    "zufp512",
    "zufp64",
    "zufp8",
    "zufp80",
  ],
  "malterlib-keyword-builtin-integer-types": [
    "__int16",
    "__int32",
    "__int64",
    "__int8",
    "aint",
    "int",
    "int1024",
    "int128",
    "int16",
    "int160",
    "int2048",
    "int256",
    "int32",
    "int4096",
    "int512",
    "int64",
    "int8",
    "int80",
    "int8192",
    "mint",
    "size_t",
    "smint",
    "uaint",
    "uint1024",
    "uint128",
    "uint16",
    "uint160",
    "uint2048",
    "uint256",
    "uint32",
    "uint4096",
    "uint512",
    "uint64",
    "uint8",
    "uint80",
    "uint8192",
    "umint",
    "zamint",
    "zint1024",
    "zint128",
    "zint16",
    "zint160",
    "zint2048",
    "zint256",
    "zint32",
    "zint4096",
    "zint512",
    "zint64",
    "zint8",
    "zint80",
    "zint8192",
    "zmint",
    "zsmint",
    "zuamint",
    "zuint1024",
    "zuint128",
    "zuint16",
    "zuint160",
    "zuint2048",
    "zuint256",
    "zuint32",
    "zuint4096",
    "zuint512",
    "zuint64",
    "zuint8",
    "zuint80",
    "zuint8192",
    "zumint",
  ],
  "malterlib-keyword-builtin-type-modifiers": ["long", "short", "signed", "unsigned"],
  "malterlib-keyword-builtin-types": ["bint", "bool", "void", "zbint", "zbool"],
  "malterlib-keyword-builtin-vector-types": ["__m128", "__m128d", "__m128i", "__m64", "__w64"],
  "malterlib-keyword-casts": ["const_cast", "dynamic_cast", "reinterpret_cast", "static_cast"],
  "malterlib-keyword-clr": [
    "__abstract",
    "__box",
    "__delegate",
    "__gc",
    "__hook",
    "__identifier",
    "__nogc",
    "__pin",
    "__property",
    "__sealed",
    "__try_cast",
    "__unhook",
    "__value",
    "abstract",
    "array",
    "delegate",
    "event",
    "friend_as",
    "gcnew",
    "generic",
    "initonly",
    "interface",
    "interior_ptr",
    "literal",
    "ref",
    "safecast",
    "value",
  ],
  "malterlib-keyword-control-statement": [
    "assume",
    "break",
    "case",
    "constant_int64",
    "constant_uint64",
    "continue",
    "default",
    "do",
    "else",
    "for",
    "goto",
    "if",
    "likely",
    "return",
    "switch",
    "unlikely",
    "while",
    "yield_cpu",
  ],
  "malterlib-keyword-exception-handling": [
    "__except",
    "__finally",
    "__leave",
    "__raise",
    "__try",
    "catch",
    "finally",
    "throw",
    "try",
  ],
  "malterlib-keyword-introspection": ["__alignof", "__uuidof", "decltype", "sizeof", "typeid"],
  "malterlib-keyword-namespace": ["namespace"],
  "malterlib-keyword-new-delete": ["delete", "new"],
  "malterlib-keyword-operator": ["operator"],
  "malterlib-keyword-optimization": ["__asm", "__assume"],
  "malterlib-keyword-other": [
    "__event",
    "__if_exists",
    "__if_not_exists",
    "__interface",
    "__multiple_inheritance",
    "__noop",
    "__single_inheritance",
    "__super",
    "__virtual_inheritance",
  ],
  "malterlib-keyword-property-modifiers": [
    "__attribute__",
    "__based",
    "__cdecl",
    "__declspec",
    "__fastcall",
    "__forceinline",
    "__inline",
    "__pragma",
    "__restrict__",
    "__stdcall",
    "__thiscall",
    "__unaligned",
    "align_cacheline",
    "assure_used",
    "calling_convention_c",
    "carries_dependency",
    "cdecl",
    "constexpr",
    "deprecated",
    "dllexport",
    "dllimport",
    "explicit",
    "fallthrough",
    "fastcall",
    "function_does_not_return",
    "ignore",
    "inline",
    "inline_always",
    "inline_always_debug",
    "inline_always_lambda",
    "inline_extralarge",
    "inline_large",
    "inline_medium",
    "inline_never",
    "inline_never_debug",
    "inline_small",
    "intrinsic",
    "mark_artificial",
    "mark_no_coroutine_debug",
    "mark_nodebug",
    "maybe_unused",
    "module_export",
    "module_import",
    "naked",
    "no_unique_address",
    "nodiscard",
    "noexcept",
    "noinline",
    "noreturn",
    "nothrow",
    "novtable",
    "only_parameters_aliased",
    "optimize_for_synchronized",
    "property",
    "return_not_aliased",
    "selectany",
    "stdcall",
    "str_utf16",
    "str_utf32",
    "str_utf8",
    "thread",
    "uuid",
    "variable_not_aliased",
  ],
  "malterlib-keyword-pure": ["pure"],
  "malterlib-keyword-qualifier": ["const", "volatile"],
  "malterlib-keyword-static-assert": ["static_assert"],
  "malterlib-keyword-storage-class": ["extern", "mutable", "register", "static"],
  "malterlib-keyword-template": ["template"],
  "malterlib-keyword-this": ["this"],
  "malterlib-keyword-type-specification": ["class", "enum", "struct", "union"],
  "malterlib-keyword-typedef": ["typedef"],
  "malterlib-keyword-typename": ["typename"],
  "malterlib-keyword-using": ["using"],
  "malterlib-keyword-virtual": ["final", "override", "sealed", "virtual"],
  "malterlib-macro": ["assert"],
  "malterlib-member-constant-public": ["npos"],
  "malterlib-member-function-public": [
    "assign",
    "at",
    "back",
    "before_begin",
    "bucket",
    "bucket_count",
    "bucket_size",
    "c_str",
    "capacity",
    "cbefore_begin",
    "clear",
    "compare",
    "compare_exchange_strong",
    "compare_exchange_weak",
    "copy",
    "count",
    "data",
    "emplace",
    "emplace_after",
    "emplace_back",
    "emplace_front",
    "emplace_hint",
    "empty",
    "equal_range",
    "erase",
    "erase_after",
    "exchange",
    "fetch_add",
    "fetch_and",
    "fetch_or",
    "fetch_sub",
    "fetch_xor",
    "fill",
    "find",
    "find_first_not_of",
    "find_first_of",
    "find_last_of",
    "fint_last_not_of",
    "front",
    "get_allocator",
    "hash_fuction",
    "insert",
    "insert_after",
    "is_lock_free",
    "key_comp",
    "key_eq",
    "length",
    "load",
    "load_factor",
    "lower_bound",
    "max_bucket_count",
    "max_load_factor",
    "max_size",
    "merge",
    "pop",
    "pop_back",
    "pop_front",
    "push",
    "push_back",
    "push_front",
    "rehash",
    "remove",
    "remove_if",
    "reserve",
    "resize",
    "reverse",
    "rfind",
    "shrink_to_fit",
    "size",
    "sort",
    "splice",
    "splice_after",
    "store",
    "substr",
    "top",
    "unique",
    "upper_bound",
    "value_comp",
  ],
  "malterlib-namespace": ["std"],
  "malterlib-preprocessor-directive": [
    "define",
    "defined",
    "elif",
    "endif",
    "error",
    "ifdef",
    "ifndef",
    "import",
    "include",
    "line",
    "once",
    "pragma",
    "undef",
  ],
  "malterlib-template-type": [
    "add_const",
    "add_cv",
    "add_lvalue_reference",
    "add_pointer",
    "add_rvalue_reference",
    "add_volatile",
    "aligned_storage",
    "aligned_union",
    "alignment_of",
    "allocator",
    "atomic",
    "auto_ptr_ref",
    "basic_filebuf",
    "basic_fstream",
    "basic_ifstream",
    "basic_ofstream",
    "basic_string",
    "char_traits",
    "common_type",
    "conditional",
    "decay",
    "default_delete",
    "deque",
    "enable_if",
    "enable_shared_from_this",
    "extent",
    "forward_list",
    "function",
    "has_virtual_destructor",
    "integral_constant",
    "is_abstract",
    "is_arithmetic",
    "is_array",
    "is_assignable",
    "is_base_of",
    "is_class",
    "is_compound",
    "is_const",
    "is_constructible",
    "is_convertible",
    "is_copy_assignable",
    "is_copy_constructible",
    "is_default_constructible",
    "is_destructible",
    "is_empty",
    "is_enum",
    "is_floating_point",
    "is_function",
    "is_fundamental",
    "is_integral",
    "is_literal_type",
    "is_lvalue_reference",
    "is_member_function_pointer",
    "is_member_object_pointer",
    "is_member_pointer",
    "is_move_assignable",
    "is_move_constructible",
    "is_nothrow_assignable",
    "is_nothrow_constructible",
    "is_nothrow_copy_assignable",
    "is_nothrow_copy_constructible",
    "is_nothrow_default_constructible",
    "is_nothrow_destructible",
    "is_nothrow_move_assignable",
    "is_nothrow_move_constructible",
    "is_object",
    "is_pod",
    "is_pointer",
    "is_polymorphic",
    "is_reference",
    "is_rvalue_reference",
    "is_same",
    "is_scalar",
    "is_signed",
    "is_standard_layout",
    "is_trivial",
    "is_trivially_assignable",
    "is_trivially_constructible",
    "is_trivially_copy_assignable",
    "is_trivially_copy_constructible",
    "is_trivially_copyable",
    "is_trivially_default_constructible",
    "is_trivially_destructible",
    "is_trivially_move_assignable",
    "is_trivially_move_constructible",
    "is_union",
    "is_unsigned",
    "is_void",
    "is_volatile",
    "list",
    "make_signed",
    "make_unsigned",
    "map",
    "multimap",
    "multiset",
    "owner_less",
    "pair",
    "priority_queue",
    "queue",
    "rank",
    "remove_all_extents",
    "remove_const",
    "remove_cv",
    "remove_extent",
    "remove_pointer",
    "remove_reference",
    "remove_volatile",
    "result_of",
    "set",
    "shared_ptr",
    "stack",
    "tuple",
    "underlying_type",
    "unique_ptr",
    "unordered_map",
    "unordered_multimap",
    "unordered_multiset",
    "unordered_set",
    "vector",
    "weak_ptr",
  ],
  "malterlib-type": [
    "CFStr",
    "CFUStr",
    "CFWStr",
    "allocator_type",
    "atomic_flag",
    "char_type",
    "const_iterator",
    "const_local_iterator",
    "const_pointer",
    "const_reference",
    "const_reverse_iterator",
    "difference_type",
    "false_type",
    "filebuf",
    "fstream",
    "hasher",
    "ifstream",
    "int_type",
    "iterator",
    "key_compare",
    "key_equal",
    "key_type",
    "local_iterator",
    "mapped_type",
    "off_type",
    "ofstream",
    "pointer",
    "pos_type",
    "reference",
    "reverse_iterator",
    "size_type",
    "state_type",
    "string",
    "traits_type",
    "true_type",
    "type",
    "u16string",
    "u32string",
    "value_compare",
    "value_type",
    "wfilebuf",
    "wfstream",
    "wifstream",
    "wofstream",
    "wstring",
  ],
} as const

export const special = {
  "[[": {
    cap: "malterlib-keyword-property-modifiers-brackets",
    raw: '"[["',
  },
  "]]": {
    cap: "malterlib-keyword-property-modifiers-brackets",
    raw: '"]]"',
  },
  auto: {
    cap: "malterlib-keyword-auto",
    raw: "(auto)",
  },
  this: {
    cap: "malterlib-keyword-this",
    raw: "(this)",
  },
  inline: {
    cap: "malterlib-keyword-property-modifiers",
    raw: '"inline"',
  },
  static: {
    cap: "malterlib-keyword-storage-class",
    raw: '"static"',
  },
  friend: {
    cap: "malterlib-keyword-access",
    raw: '"friend"',
  },
  private: {
    cap: "malterlib-keyword-access",
    raw: '"private"',
  },
  protected: {
    cap: "malterlib-keyword-access",
    raw: '"protected"',
  },
  public: {
    cap: "malterlib-keyword-access",
    raw: '"public"',
  },
  class: {
    cap: "malterlib-keyword-type-specification",
    raw: '"class"',
  },
  concept: {
    cap: "malterlib-keyword-type-specification",
    raw: '"concept"',
  },
  enum: {
    cap: "malterlib-keyword-type-specification",
    raw: '"enum"',
  },
  namespace: {
    cap: "malterlib-keyword-namespace",
    raw: '"namespace"',
  },
  struct: {
    cap: "malterlib-keyword-type-specification",
    raw: '"struct"',
  },
  template: {
    cap: "malterlib-keyword-template",
    raw: '"template"',
  },
  union: {
    cap: "malterlib-keyword-type-specification",
    raw: '"union"',
  },
  "#if": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#if"',
  },
  "#ifdef": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#ifdef"',
  },
  "#ifndef": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#ifndef"',
  },
  "#elif": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#elif"',
  },
  "#else": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#else"',
  },
  "#endif": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#endif"',
  },
  "#define": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#define"',
  },
  "#include": {
    cap: "malterlib-preprocessor-directive",
    raw: '"#include"',
  },
} as const
